repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.0
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.10.0
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: update-code-line-statistics
        name: update README code line statistics
        entry: bash -c 'python3 scripts/count_code_lines.py --update-readme README.md && git add README.md'
        language: system
        pass_filenames: false
