"""initial

Revision ID: c9ce20c8a1b2
Revises: 
Create Date: 2026-04-26 10:31:16.389509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9ce20c8a1b2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('operator', sa.String(length=100), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('change_logs', schema=None) as batch_op:
        batch_op.create_index('idx_changelog_created', ['created_at'], unique=False)
        batch_op.create_index('idx_changelog_entity', ['entity_type', 'entity_id'], unique=False)

    op.create_table('network_plane_types',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('network_plane_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_network_plane_types_name'), ['name'], unique=True)

    op.create_table('regions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regions_name'), ['name'], unique=True)

    op.create_table('ip_allocations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('region_id', sa.String(length=36), nullable=False),
    sa.Column('plane_type_id', sa.String(length=36), nullable=False),
    sa.Column('ip_range', sa.String(length=43), nullable=False),
    sa.Column('vlan_id', sa.Integer(), nullable=True),
    sa.Column('gateway', sa.String(length=39), nullable=True),
    sa.Column('subnet_mask', sa.String(length=15), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plane_type_id'], ['network_plane_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ip_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ip_allocations_plane_type_id'), ['plane_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ip_allocations_region_id'), ['region_id'], unique=False)

    op.create_table('region_network_planes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('region_id', sa.String(length=36), nullable=False),
    sa.Column('plane_type_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plane_type_id'], ['network_plane_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_id', 'plane_type_id', name='uq_region_plane')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('region_network_planes')
    with op.batch_alter_table('ip_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ip_allocations_region_id'))
        batch_op.drop_index(batch_op.f('ix_ip_allocations_plane_type_id'))

    op.drop_table('ip_allocations')
    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regions_name'))

    op.drop_table('regions')
    with op.batch_alter_table('network_plane_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_network_plane_types_name'))

    op.drop_table('network_plane_types')
    with op.batch_alter_table('change_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_changelog_entity')
        batch_op.drop_index('idx_changelog_created')

    op.drop_table('change_logs')
    # ### end Alembic commands ###
